(in-package :graphviz)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; here are some hand made overrides for the swig
;;; generated file

(defcstruct Agnode_t
	;(tag :int)
	;(pad :int :offset 4)
	(handle :int)
	(attr :pointer)
	(name :string)
	(id :int)
	(graph :pointer)
	(u :pointer))

(defcstruct Agedge_t
	;(tag :int)
	;(printkey :int)
	(handle :int)
	(attr :pointer)
	(head :pointer)
	(tail :pointer)
	(id :int)
	(u :pointer))

(defcstruct bezier
	(list :pointer)
	(size :int)
	(sflag :int)
	(eflag :int)
	;(sp :pointer)
        ;(ep :pointer)
        (spx :int)
        (spy :int)
	(epx :int)
        (epy :int))

(defcstruct Agraph_t
	;(tag :int)
	;(kind :int)
	(handle :int)
	(attr :pointer)
	(name :string)
	(univ :pointer)
	(nodes :pointer)
	(inedges :pointer)
	(outedges :pointer)
	(root :pointer)
	(meta_node :pointer)
	(proto :pointer)
	(u :pointer))

(defcstruct Agnodeinfo_t
	(shape :pointer)
	(shape_info :pointer)
	;(coord :pointer)
        (xcoord :int)
        (ycoord :int)
	(width :double)
	(height :double)
	;(bb :pointer)
        (bb-lower-left-x :double)
        (bb-lower-left-y :double)
        (bb-upper-right-x :double)
        (bb-upper-right-y :double)
	(ht :int)
	(lw :int)
	(rw :int)
	(label :pointer)
	(alg :pointer)
	(state :char)
	(gui_state :unsigned-char)
	(clustnode :pointer)
	(pinned :pointer)
	(xsize :short)
	(ysize :short)
	(id :int)
	(heapindex :int)
	(hops :int)
	(pos :pointer)
	(dist :double)
	(showboxes :pointer)
	(has_port :pointer)
	(node_type :char)
	(mark :char)
	(onstack :char)
	(ranktype :char)
	(weight_class :char)
	(next :pointer)
	(prev :pointer)
	(in :pointer)
	(out :pointer)
	(flat_out :pointer)
	(flat_in :pointer)
	(other :pointer)
	(clust :pointer)
	(UF_size :int)
	(UF_parent :pointer)
	(inleaf :pointer)
	(outleaf :pointer)
	(rank :int)
	(order :int)
	(mval :int)
	(save_in :pointer)
	(save_out :pointer)
	(tree_in :pointer)
	(tree_out :pointer)
	(par :pointer)
	(low :int)
	(lim :int)
	(priority :int)
	(pad :pointer))

